default: &default
  max_tweets_to_save:
    free: 10
    paid: 50
  max_tweets_to_collect: 50

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  max_tweets_to_save:
    free: 100
    paid: 400
  max_tweets_to_collect: 800
