collect:
  name: Collect tweets every minute
  cron: "*/1 * * * *"
  class: Crawlers::Tokens::CollectTweetsWorker

svm:
  name: Predict with SVM every 15 minutes
  cron: '*/15 * * * *'
  class: SvmWorker

statistics:
  name: Update stats of token
  cron: "0 * * * *"
  class: StatisticsWorker

links_title:
  name: Crawler title to all public tokens at 4h
  cron: "0 4 * * *"
  class: CrawlerLinksWorker
